### ISSUE TITLE
New Information

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#125]
Happy New Year :fireworks: 

Let get this thing rolling! Whats the new information for the the first JS.LA for this year.

**Comment by jcblw** [comment]
heres the info I have.

@helior is going to be doing the module of the month on https://github.com/cjohansen/Sinon.JS

**Comment by emkay** [comment]
@jcblw I'm still waiting to hear back about the venue. Trying to get Yahoo room as backup.

**Comment by davidguttman** [comment]
#1

Speaker: Demetrios Papadopoulos
Title: Lovefield: a powerful Javascript SQL-like database query engine
for the web.

Abstract:
Lovefield is providing a feature rich, cross-browser database query
engine built using IndexedDB as a backend. It provides an intuitive
SQL-like declarative syntax and it is closing a gap in the web
development ecosystem that was created by the deprecation of WebSQL
back in 2010.

G+: https://plus.google.com/+DemetriosPapadopoulos
Github: https://github.com/google/lovefield

**Comment by jcblw** [comment]
:+1:

**Comment by emkay** [comment]
We are good to go with the space at Y! so we can announce.

**Comment by davidguttman** [comment]
Great, I should get the info for the second talk today.

**Comment by jcblw** [comment]
Nice I'll start setting up all the info into the new template, any news on
sponsors? besides Yahoo.

**Comment by emkay** [comment]
I'm guessing verizon, but not positive. cc: @flores

**Comment by flores** [comment]
I can't confirm Verizon until next week unfortunately.

**Comment by davidguttman** [comment]
Talk 2

Speaker: Jason Farrell
Title: How to effortlessly integrate Three.js into your projects

Abstract:
This talk will focus on how to add 3D animation to real-world projects.
It'll cover the basics of how to get started with Three.js, and how to
build animated interactions that can be used in seemingly normal web apps.

Avatar: http://ua5.co/image/3q3L2a14213S (1000x1000px)
https://twitter.com/jasonfarrell
https://github.com/jasonfarrell

**Comment by jcblw** [comment]
who can make a tito url? @jsla/owners
