### ISSUE TITLE
drinks.js

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#126]
branding.js

![drinks](https://cloud.githubusercontent.com/assets/578259/5625157/072a0240-952a-11e4-9c61-d30ff26da151.png)

whats everyone think? I gonna make a small component for the site, and was thinking it would be awesome to have some more visuals for it.

Obvious inspiration.

![global_243993072](https://cloud.githubusercontent.com/assets/578259/5625187/9e0d32cc-952a-11e4-9986-e9f96d690b21.jpeg)

**Comment by emkay** [comment]
I really like this. :sake:

**Comment by davidguttman** [comment]
Badass, great job.

**Comment by jcblw** [comment]
![screenshot from 2015-01-06 21 43 16](https://cloud.githubusercontent.com/assets/578259/5641414/86ae2776-95ed-11e4-859b-b51aa38d7809.png)

little drinksjs ad.
