### ISSUE TITLE
rich snippets

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#130]
this would be a great addition pretty simple to implement as well.

https://support.google.com/webmasters/answer/99170?hl=en

**Comment by cardoni** [comment]
Preview:
![Preview of rich snippets](https://www.dropbox.com/s/yj0fiexbchu4dcy/Screenshot%202015-01-12%2016.29.09.png?dl=1)

**Comment by flores** [comment]
FYI, this group of issues merged and closed by @emkay are live.

**Comment by jcblw** [comment]
woot. @emkay  & @flores  thanks!
