### ISSUE TITLE
February Information

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#141]
Time to start compiling the data!

**Comment by jcblw** [comment]
@jsla/owners  woops forgot to mention everyone, @cardoni you wanna add your info here for MOTM

**Comment by davidguttman** [comment]
PhantomJS Under the Hood

This talk goes into lessons learned from writing a sizeable PhantomJS application. We'll examine the architecture of the PhantomJS application itself and what the implications are for developers. We'll also look at best practices for using 3rd party libraries and running unit tests.

https://github.com/xbudex/
@xbudex

https://en.gravatar.com/avatar/1521736f593847ef597a98ebfabbabc5.jpg
https://en.gravatar.com/avatar/1521736f593847ef597a98ebfabbabc5.jpg?s=2048

**Comment by davidguttman** [comment]
* Your github acct
https://github.com/advait
 
* Your twitter acct
https://twitter.com/advait3000
…
 
* Link to preferred avatar image
https://avatars2.githubusercontent.com/u/504011?v=3&s=460
(Let me know if you want better quality) 
…
 
* A temporary/plausible talk title (we can change this after Tues)
Monitoring Applications with StatsD
…
 
* A temporary/plausible abstract (we can change this after Tues)
StatsD is a generic, lightweight, flexible protocol/daemon that allows you to keep track of application-specific time series metrics. It's a dead-simple approach that enables developers to instrument their applications with granular monitoring before even deploying to production.

**Comment by jcblw** [comment]
@davidguttman  thanks,still pending @bjoshuanoah info for venue and our second sponsor
