### ISSUE TITLE
March Information

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#146]
Lets get ready for March @jsla/developers .

**Comment by davidguttman** [comment]
Github: github.com/willsen
Twitter: twitter.com/willsentance
Avatar: http://i.cubeupload.com/hrGpPD.jpeg
Talk Title: How launching Icecomm on HN created the most curious chat
roulette ever (and how you can too)
Talk abstract: Icecomm lets you take full advantage of WebRTC in under 10
lines of frontend javascript. Learn how to use Icecomm to build a multiway
video chat app in minutes without worrying about backend code. To get us
started I'll explain some Icecomm basics, we'll live code the video chat
app together and we'll even give you a sneak peak of a brand new Icecomm
SDK that lets you add video and audio chat right inside emails

**Comment by jcblw** [comment]
@davidguttman  you said you want to do module of the month right?

**Comment by davidguttman** [comment]
Yep

**Comment by jcblw** [comment]
@davidguttman cool, so Ill put you in for ReactPivot

**Comment by davidguttman** [comment]
Twitter: calleynye
Avatar: http://calley.co/wp-content/uploads/2013/07/me-250x250.jpg
Title: UX for Developers
Abstract: 
What good is it to make an app if no one will use it? This talk will aim to demystify the broad discipline of user experience, and introduce some core concepts and methods. These concepts will help you develop a useable application, acquire users and keep them coming back for more.

**Comment by emkay** [comment]
Host: Codesmith
Url: http://www.codesmith.io/
Address: 5300 Beethoven Street, Los Angeles, CA

**Comment by jcblw** [comment]
added just about all the information in just need to add the ti.to url once I make one. https://github.com/jsla/js.la/tree/info/march2015

**Comment by jcblw** [comment]
this is done!
