### ISSUE TITLE
April Info

### ISSUE THREAD

**Issue by davidguttman** [jsla/js.la#149]
Name: Paul Frazee

Github: pfraze

Twitter: twitter.com/pfrazee

Avatar: https://cloud.githubusercontent.com/assets/1270099/6828987/bc3a4392-d2de-11e4-8009-01a301ff3ed6.png

Title: Decentralized Databases, and the End of the Web Host

Abstract:
How do we synchronize user devices without using servers or central coordination? Join us for a discussion of content-addressing, secure data structures, the web of trust, and apps-development in a post-host Web.

**Comment by jcblw** [comment]
woot! I would love to get enough info to have this up by the event tomorrow :smile:

**Comment by jcblw** [comment]
The venue is Sapient Nitro, also

> dguttman [4:17 PM] 
> @jcblw: if Ben doesn't get me his info by tomorrow
>
> dguttman [4:18 PM]
> we can just put TBD for his title/abstract

**Comment by jcblw** [comment]
@davidguttman  we get any more info on this?

**Comment by davidguttman** [comment]
Here's Ben's info:

title: npm-Registry@2.0
description: npm has been in the process of rewriting their backend infrastructure. Ben, lead developer of the registry, will be talking to you about the motivations for the rewrite, and the approach that has been taken.

**Comment by jcblw** [comment]
nice, pushed!
