### ISSUE TITLE
June 2015 Info

### ISSUE THREAD

**Issue by davidguttman** [jsla/js.la#157]
Twitter: @nebrius
GitHub: bryan-m-hughes
Image: https://theoreticalideations.com/static/me.jpg

Successfully Hacking in Your Spare Time

Hacking in your spare time is a lot of fun, but how do you actually finish that project you've been dreaming about? Personal hacking has different constraints and requirements than coding for a job. The most successful personal projects are ones that embrace these differences.

This talk will discuss these constraints and requirements, and how a little creativity goes a long way. Key to this is dreaming big while being realistic, and just getting something out there is important. I will also discuss the role of open source in personal projects, from leveraging existing work to how you actually open source a project properly.

Finally, I will discuss personal hacking within the context of a broader community, how the community can help and support you, and generally how awesome it feels to be part of something bigger.

**Comment by davidguttman** [comment]
Twitter: @ktslwy

Github: https://github.com/ktslwy

Avatar: https://media.licdn.com/media/p/4/000/154/1a0/0deba25.jpg

Title: Scalable and Maintainable React

Abstract: React is created for building large web applications with data that changes in response to actions over time. This is exactly what many of our user-facing products are doing. Yet like many other application frameworks, scalability and maintainability are not inherent, because you are still free to organize your application as long as you follow the unidirectional flow. The application could be storing duplicate data in multiple places, action handlers could be interfering with each other, reusable parts could be colliding, mishandled state management could be causing infinite render cycle and race condition. Application development could be much easier when scalability and maintainability are taken into account not after but during the process. This talk will share lessons learned from my React application development with code samples at different stages of the unidirectional flow with the goal to truly take advantage of React to build a scalable and maintainable application.

**Comment by jcblw** [comment]
the venue and one of the sponsors is Google.
