### ISSUE TITLE
New JSLA logo

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#161]
Lets get a thread to get some ideas flowing! So we have been talking about this for a while now. We need a logo of our own not just a revision of the JS logo.

**Comment by jcblw** [comment]
![jsla-sun](https://cloud.githubusercontent.com/assets/578259/8634860/18a34306-27bf-11e5-96c9-286786933a1d.png)

I was working on this one, pretty much stole the flag from an LA flag redesign contest. 
http://laimyours.com/53799/and-our-new-los-angeles-flag-is/

**Comment by jcblw** [comment]
Some inspiration.

![EmpireJS](http://empirejs.org/img/js-marquee.png)

**Comment by d48** [comment]
regarding type, and just a question to help think if one is more important than the other, or if they should be equal in visual weight: should there be more emphasis on either JavaScript or Los Angeles?

**Comment by jcblw** [comment]
@d48 we initially emphasized `JS` in our old logo. I think that was because we essentially took the JS logo and superimposed  `.LA`. I'm sure with such a small amount of chars would we put emphasis on a part of the text. Just my opinion tho, I can be swayed.

**Comment by d48** [comment]
awesome. i'm super biased because i love living in LA. so my biased opinion would to make LA have more emphasis :) but it is about js in la so i think equal weight works. lowercase looks cool and modern

**Comment by jcblw** [comment]
<3 LA! :+1:

**Comment by emkay** [comment]
@jcblw :+1: I'm a fan of the lowercase, but not sure I love the round corners.

**Comment by Omarcito** [comment]
That node school logo you guys came up with is rad. Is there anything similar to that idea you can play with? What other landmark could you use to make it clearly LA?

**Comment by Omarcito** [comment]
I also really dig the idea of it being center weighted like you have in those examples. It seems like a lot of places are making avatars circles now and the current logo is being cut off.

**Comment by jcblw** [comment]
yeah @Omarcito i wish there was something that would be iconic for LA, but I do not know if there is without getting too hollywood. 

Here is another cool site that the designer at my work showed me. http://www.onthegrid.city/

I really like the LAX building icon stuff, really reminds me of the nodeschool logo style.

**Comment by Omarcito** [comment]
@jcblw oh yea the LAX revolving restaurant is great. Now is there a way to use something like that without totally ripping off that site?...

**Comment by d48** [comment]
^ that onthegrid style looks cool, kind of like an old-school, 8-bit style atari game line work

**Comment by jcblw** [comment]
some more LA landmark porn.

![4680849315_70012a97b6_b](https://cloud.githubusercontent.com/assets/578259/8705453/997f7914-2ade-11e5-8b8a-1ea18cb76963.jpg)
![34c50b29def4addc98b1c36f27642689](https://cloud.githubusercontent.com/assets/578259/8705461/9d6e1350-2ade-11e5-835f-06f5c0c74e3e.jpg)

**Comment by d48** [comment]
Yea this looks fresh, when I think about LA for landmarks the ones that standout the most are LAX and the Hollywood sign.

**Comment by jcblw** [comment]
Took a shot at making the LAX version.

![jsla-logo airport](https://cloud.githubusercontent.com/assets/578259/8869493/2940ceca-3199-11e5-9ec4-5d0226475f1a.png)

**Comment by Omarcito** [comment]
i like the direction. only thoughts are maybe less planes, and make the arches/restaurant fill more of the space.

**Comment by ashwell** [comment]
We should probably make a move on one of these, I think I'm liking the lowercase type, but when I try to think up a quintessential "LA" image all I can think of is freeways...

**Comment by jcblw** [comment]
I think the only thing that is holding this up is the white bg, for now maybe just remove that until we get something good?

![basic-jsla](https://cloud.githubusercontent.com/assets/578259/14450813/9d7a8454-0036-11e6-899f-367112b97ec9.png)

**Comment by d48** [comment]
imo the subtle change from uppercase to lowercase works great. #shipit is my vote

**Comment by etanlubeck** [comment]
:shipit:

**Comment by ashwell** [comment]
I went ahead and put the new logo into the update for nodeschool page, https://github.com/nodeschool/los-angeles/pull/69

**Comment by jcblw** [comment]
closing this, will reopen when working on the logo again.
