### ISSUE TITLE
Design for Individual Event/Individual Speaker Pages

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#168]
This will help with SEO and share-ability of our site. Right now on [feature/individual-events](https://github.com/jsla/js.la/tree/feature/individual-events) branch there is the ability to generate pages for individual event and for individual speakers of those events. The designs are not really optimized for the amount of information that is there or for the way we can now highlight the videos. Along with designing these pages there should be ways to link into these pages as well as the cta to share.

<img width="670" alt="screen shot 2015-10-11 at 9 17 58 pm" src="https://cloud.githubusercontent.com/assets/578259/10421452/9f6701fc-705d-11e5-8407-a985ce038940.png">
<img width="747" alt="screen shot 2015-10-11 at 9 11 54 pm" src="https://cloud.githubusercontent.com/assets/578259/10421446/79a280b8-705d-11e5-8a92-967ee73ffa8e.png">

**Comment by davidguttman** [comment]
Awesome! Thank you so much for starting on this!

**Comment by jcblw** [comment]
Made some mockups of what I think could be a cool layout for the single speaker page

![single speaker page](https://cloud.githubusercontent.com/assets/578259/11022424/65e2569a-8613-11e5-99f6-82c661b90365.png)

Pretty much made the video king of the content. If we have a page that does not have a video we can just remove the black bar.

The links to the date would all reference back to the event page. Still pending design but I think that would just be similar to the front page.

I like the idea of adding the other speaker to the page I think it still needs some work to make it look more clickable.

Also on this page I'm thinking it would be good to make a new component that we can scatter around other pages.

![join jsla component](https://cloud.githubusercontent.com/assets/578259/11022446/34f61d5e-8614-11e5-9ccc-370e80c80138.png)

This is the list form of the current button group but also allows us to reuse some styles as well as put link to twitter and github. One thing is that we should probably get #161 out of the way because the current looks a bit weird in a circle.

**Comment by Omarcito** [comment]
@jcblw I like it. 

Another "More from" idea:
What about people with multiple JSLA appearances? Would there be a way to link to their other talks?

**Comment by jcblw** [comment]
possibly it would be kinda tough tho, since I kinda am jumping down the data. There might be a way grab the initial data set and then scan all of the talks. Thats a really  good idea tho.
