### ISSUE TITLE
January 2016

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#173]
Lets get this year started! :tada: 

Ill start piecing together info here.

**Comment by emkay** [comment]
Venue: UCLA

Boelter Hall Room 3400, 580 Portola Plaza, Los Angeles, CA 90095

Specific hall address might change if we can secure a bigger one.

**Comment by jcblw** [comment]
Thanks @emkay and @davidguttman 

#### Talk 1
- Michael Jackson
- Twitter: mjackson
- Github: mjackson
- Topic: Rendering with React
- Summary: The virtual DOM abstraction created by React.js has changed the way the entire industry thinks about rendering web sites. Let's talk about what makes it special, and the cool stuff we can do with it!
- Avatar: https://avatars3.githubusercontent.com/u/92839?v=3&s=400

**Comment by davidguttman** [comment]
#### Talk 2
- David Guttman
- Twitter: davidguttman
- Github: davidguttman
- Topic: Scalable Authentication for Microservices and Single Page Apps
- Summary: Back in the dark ages of 2015, setting up authentication for microservices and SPAs was a huge PITA. Thankfully, it's now 2016 and it's dead simple. We'll go over what's needed for modern authentication and how easy it is to get it all working with Authentic.
- Avatar: https://avatars3.githubusercontent.com/u/431696?v=3&s=460

**Comment by jcblw** [comment]
:100:
