### ISSUE TITLE
March JS.LA

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#179]
ill be able to go to this one yeeeah

**Comment by jcblw** [comment]
# Speaker 1

Talk title: “Crashing the Mobile Party”
Summary: “Native Apps vs. Hybrid vs. Mobile Web. Can a single Javascript codebase be your cross-platform strategy with today’s tools? Learn through the pitfalls and successes we’ve had at PartyOn, the social music app that uses geolocation, web sockets, and music streaming to improve parties”
Website: http://www.partyonmusic.com/
Github username: bsatorius
Avatar: http://imgur.com/aEzCN7L

**Comment by jcblw** [comment]
# Sponsor

Interlincx

![logo-black](https://cloud.githubusercontent.com/assets/578259/13558107/9f15f7b4-e3b0-11e5-89c7-4dcdcc2f1cf8.png)

url: http://www.interlincx.com/

^^ @davidguttman  is there a different page to link to?

**Comment by emkay** [comment]
Host: Philosophie http://philosophie.is/

![inline_black](https://cloud.githubusercontent.com/assets/1327/13584974/e184ed4a-e46d-11e5-973c-9fa6c88b2552.png)

**Comment by jcblw** [comment]
## Speaker 2

Talk: Bringing Open-Source Practices to Your Day Job
>Description: npm has built a community that allows millions of JavaScript developers to build together on a daily basis. From this community great software development practices have emerged: unit-testing, test-coverage, modularity. In this talk Ben will discuss how, and why, you should bring these practices to work with you.
>Bio: Benjamin Coe was npm’s third employee and currently leads npm On-Site, npm’s registry product for enterprises. Ben is a core contributor to yargs, node-redis, and nyc; is passionate about open-source-software; and loves working to bring these best practices to the enterprise.

We should have all other info in the repo already.

**Comment by jcblw** [comment]
We got all the info Ill see if I can knock it out tonight!

**Comment by jcblw** [comment]
up on the site :100:
