### ISSUE TITLE
JSLA team

### ISSUE THREAD

**Issue by jcblw** [jsla/js.la#180]
we have decided to make a team page for people to help identify the JSLA team at events @jsla/developers  let me get you headshots!

**Comment by jcblw** [comment]
here is mine
![12401772_10207083585241085_1175155646242506431_o](https://cloud.githubusercontent.com/assets/578259/13473447/3f06675e-e06e-11e5-84f8-c1578ab0b67f.jpg)

**Comment by jcblw** [comment]
![etanlubeck_oh](https://cloud.githubusercontent.com/assets/578259/13476583/5cf85b6e-e07d-11e5-9e8b-f488b3d8470d.jpg)

**Comment by davidguttman** [comment]
![dguttman](https://cloud.githubusercontent.com/assets/431696/13478388/ad14a3ac-e085-11e5-8480-f4aabf848b1c.jpg)

**Comment by Omarcito** [comment]
![omar-avatar](https://cloud.githubusercontent.com/assets/1555240/13536382/6a7535b4-e1f4-11e5-81b4-45027fb86b70.jpg)

**Comment by jxson** [comment]
@Omarcito haha, great pic. :+1:

**Comment by emkay** [comment]
![5541043146_e25100196c_b](https://cloud.githubusercontent.com/assets/1327/13537554/58c798ce-e1fa-11e5-98e0-9d3ddd98de46.jpg)

**Comment by d48** [comment]
![alligot](http://content.screencast.com/users/regalado48/folders/NodeSchool/media/86b14ed7-755f-4849-8c7a-f544eb19fdc2/977061_458102757628278_376220275_o.jpg)

**Comment by d48** [comment]
or this

![alligot2](http://content.screencast.com/users/regalado48/folders/NodeSchool/media/2e421016-9964-45f3-9e0e-dbb4a1be725b/12615318_10153292770875848_4801823546578571727_o.jpg)

**Comment by jcblw** [comment]
@d48  this one will work

<img width="512" alt="screen shot 2016-03-04 at 4 16 11 pm" src="https://cloud.githubusercontent.com/assets/578259/13543885/7df3b31a-e224-11e5-9479-2fb16b705979.png">

**Comment by etanlubeck** [comment]
:shipit:

**Comment by d48** [comment]
hahahah

**Comment by jcblw** [comment]
v1 up [`team page`](http://js.la/team)

going to iterate by adding twitter and slack handles, linking to twitter

and hopefully @ashwell 's face

**Comment by jcblw** [comment]
closing this ticket @ashwell  you know what to do when you get the info

**Comment by d48** [comment]
👍

**Comment by d48** [comment]
@ashwell where is heeeeeeeee!!!!

**Comment by ashwell** [comment]
There is an old photo Spencer took at one of the events from last year.... http://farm1.static.flickr.com/691/21740526466_26d45383bd_z.jpg

**Comment by d48** [comment]
Nice

**Comment by jcblw** [comment]
@ashwell @Spencer-Allen yo, do you have a larger version of this image, currently the photos on the page are 600x600

**Comment by Spencer-Allen** [comment]
Weird. I didn't get a notification on this until just now. You can find all JS.LA photos here https://www.flickr.com/photos/jslaphotos and they all have a download link from Flickr. here's the link to that exact pic. https://www.flickr.com/photos/jslaphotos/21740526466/in/album-72157659189034465/

**Comment by jcblw** [comment]
Thanks @Spencer-Allen

**Comment by ashwell** [comment]
pinging @jcblw 

![21740526466_9a361642ea_k](https://cloud.githubusercontent.com/assets/1377889/17611349/51f38d76-5ffb-11e6-9108-9c3bd709e5d1.jpg)

**Comment by d48** [comment]
^ awesome pic
