### ISSUE TITLE
Add a Press Kit Page

### ISSUE THREAD

**Issue by ashwell** [jsla/js.la#195]
As discussed on 8/2/2016

Should contain
- [ ] icons
- [ ] images
- [ ] standard description
- [ ] contact information
- [ ] something else?

pinging @davidguttman @etanlubeck @d48 @Omarcito @jcblw

**Comment by d48** [comment]
Pulling from this for ideas of what may go in a Press Kit: https://www.entrepreneur.com/article/57260

* FAQs may be good if we do have them
* and list of standard image types and sizes for the `js.la` logos
    * Download from here is pretty cool: https://prezi.com/press/kit/
