### ISSUE TITLE
Proposal: a RSVP on Meetup Button

### ISSUE THREAD

**Issue by seanwestfall** [jsla/js.la#225]
This is in reference to this PR: https://github.com/jsla/js.la/pull/223
## GOAL
* Include a RSVP via meetup button that takes you to the event page.
* Include a counter that shows how many have signed up and how many are waitlisted (a combined counter from both ti.to and meetup).
## Motivation
* Ti.to typically sells out in hours, which means JS.LA goers, new and old, will be lead to believe they can't attend the event. A RSVP button on the main landing page to the secondary booking service, meetup.com, will give people the ability to RSVP, and encourage more people to attend the event.
* A counter will give a stronger indication to a would be attendee if it's worthwhile to try and attempt to attend the event.
* This could be a temporary solution until we build our own ticketing system.
### Overfiew
* A span has been added to `_action-buttons.jade`
* css for that span has been added to `/css/src/component/_action-buttons.less`
* the font-awesome css file, for the meetup icon, currently using the CDN

**TODO**
* javascript logic to query the ti.to and meetup.com API, or simple query and use selectors to get the relevant data from the public pages, to update the counters.
* Use a local copy o the font-awesome css file, and not the CDN

### Desktop
![screen shot 2017-05-14 at 8 50 19 pm](https://cloud.githubusercontent.com/assets/9439906/26042249/9ca0d4e8-38e8-11e7-9c18-4abb87cad4d1.png)

### Tablet
![screen shot 2017-05-14 at 8 50 35 pm](https://cloud.githubusercontent.com/assets/9439906/26042251/a25add84-38e8-11e7-956e-92e36fcdf29c.png)

### Mobile
![screen shot 2017-05-14 at 8 50 47 pm](https://cloud.githubusercontent.com/assets/9439906/26042255/a5b79f62-38e8-11e7-93e8-b3249dccc4a5.png)

**Comment by jcblw** [comment]
linking to #223  to keep references.

I think my biggest push back to this is that the meetup page would need to be setup prior to releasing a new version of the website. I would prefer we not add any road blocks to updating the site. 

I would also think this would confuse new attendee's more then help them since there is no indication of the between "RSVP for event" and "RSVP on meetup". We are giving our users more choices but there is no real reason indicated why.

**Comment by seanwestfall** [comment]
@jcblw Good point, what if we changed `RSVP for event` to `RSVP on ti.to`: 
![screen shot 2017-05-15 at 2 26 23 pm](https://cloud.githubusercontent.com/assets/9439906/26080264/8e9ad532-397a-11e7-841d-1f0994b0046a.png)

Adding updating meetup as an added step in updating the site seems like a more minor issue than our problems with ti.to selling out too fast. I feel like otherwise our reservation system is broken. Also, this is only a temporary solution till we build our own ticketing system.
