### ISSUE TITLE
Add Social Media Meta Tags

### ISSUE THREAD

**Issue by ashwell** [jsla/js.la#256]
Currently adding `https://js.la` to a tweet looks like this,

![screen shot 2017-10-26 at 2 57 08 pm](https://user-images.githubusercontent.com/1377889/32079060-0f9547c6-ba5e-11e7-8b38-96e14ab62989.png)

We should look at adding some FB Open Graph and Twitter meta tags to get some better ingestion of our page into social media sites.

**Comment by jcblw** [comment]
hmmmm, looks like it might just be twitters stuff.

https://github.com/jsla/js.la/blob/master/public/_layout.jade#L10

**Comment by jcblw** [comment]
<img width="486" alt="screen shot 2017-10-26 at 4 11 06 pm" src="https://user-images.githubusercontent.com/578259/32081142-79ce2dce-ba68-11e7-9f14-b92dc8fdc99d.png">
 
this is facebook

**Comment by ashwell** [comment]
god damn it twitter

may still be worth adding the twitter specific meta tags

**Comment by ashwell** [comment]
also the FBOG ones would allow us to select the image to use and size of the embed and such

**Comment by jcblw** [comment]
def just writing this down here to make sure to scope it.
